os: linux
dist: focal
services:
  - docker
language: python

stages:
  - test
  - name: "release"
    if: type = push

jobs:
  include:
    - stage: test
      name: "Test"
      if: type = pull_request
      install:
        - pip install mkdocs-material
      script:
        - mkdocs build

    - stage: "publish"
      name: "publish" 
      if: branch = master
      language: node_js
      node_js:
        - 17
      env:
        - IMAGE=pivpn/docs
      install:
        - pip install mkdocs-material
        - npm install @semantic-release/github -D
        - npm install @semantic-release/changelog -D
        - npm install @semantic-release-plus/docker -D
      before_script:
        - echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
      script:
        - mkdocs build
        - docker build -t $IMAGE .
        - npx semantic-release

