os: linux
dist: focal
language: python
services:
  - docker

stages:
  - test
  - name: "release"
    if: type = push

jobs:
  include:
    - stage: test
      name: "Test"
      if: type = pull_request
      install:
        - pip install mkdocs-material
      script:
        - mkdocs build

    - stage: "publish"
      name: "publish" 
      if: branch = master
      env:
        - IMAGE=pivpn/docs
      before_install:
        - curl -fsSL https://deb.nodesource.com/setup_16.x | sudo -E bash - 
        - sudo apt-get install -y nodejs
        - node --version
      install:
        - pip install mkdocs-material
        - npm install @semantic-release/github -D
        - npm install @semantic-release/changelog -D
        - npm install @semantic-release-plus/docker -D
      before_script:
        - echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
        - echo $PWD
        - ls -la
      script:
        - docker build -t $IMAGE .
        - npx semantic-release

