os: linux
dist: focal
language: python
services:
  - docker

stages:
  - test
  - name: "release"
    if: branch = master

jobs:
  include:
    - stage: test
      name: "Test"
      if: type = pull_request
      install:
        - pip install mkdocs-material
      script:
        - mkdocs build

    - stage: "publish"
      name: "publish" 
      if: type = push
      env:
        - IMAGE=pivpn/docs
      before_install:
        - apt update
        - apt install -y curl
        - curl -fsSL https://deb.nodesource.com/setup_17.x | bash - 
        - apt-get install -y nodejs
      install:
        - pip install mkdocs-material
        - npm install @semantic-release/github -D
        - npm install @semantic-release/changelog -D
        - npm install @semantic-release-plus/docker -D
      before_script:
        - echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
      script:
        - docker build -t $IMAGE .
        - npx semantic-release

